/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/algebra/solve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Solve Equation Endpoint
         * @description Solve or analyze an algebraic equation via the pure S1 application service.
         */
        post: operations["solve_algebra_v1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health Check Endpoint
         * @description Observational health check deriving counts dynamically from underlying domain registries.
         */
        get: operations["health_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/concepts/{concept_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Concept Endpoint
         * @description Retrieves an immutable ConceptKnowledge definition by its canonical ID.
         */
        get: operations["get_knowledge_concept_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/formulas/{formula_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Formula Endpoint
         * @description Retrieves an immutable FormulaKnowledge definition by its canonical ID.
         */
        get: operations["get_knowledge_formula_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/graph": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Knowledge Graph Endpoint
         * @description Exports the complete 29-node / 84-edge mathematical knowledge graph.
         */
        get: operations["get_knowledge_graph_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/methods/{method_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Method Endpoint
         * @description Retrieves an immutable MethodKnowledge definition by its canonical ID.
         */
        get: operations["get_knowledge_method_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/knowledge/theorems/{theorem_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Theorem Endpoint
         * @description Retrieves an immutable TheoremKnowledge definition by its canonical ID.
         */
        get: operations["get_knowledge_theorem_v1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * AnalyzedNoExecutionResponse
         * @description Response state when problem is analyzed but no trace executed (e.g. unavailable method selected or degenerate linear).
         */
        AnalyzedNoExecutionResponse: {
            /** Analysis Message Vi */
            analysis_message_vi: string;
            /** Available Methods */
            available_methods?: components["schemas"]["MethodOptionView"][];
            degenerate_solution?: components["schemas"]["DegenerateSolutionView"] | null;
            /** Problem */
            problem: components["schemas"]["CanonicalQuadraticProblemView"] | components["schemas"]["CanonicalDegenerateProblemView"];
            reason_code: components["schemas"]["NoExecutionReasonCode"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            response_status: "ANALYZED_NO_EXECUTION";
            /** Selected Method Id */
            selected_method_id?: string | null;
        };
        /**
         * ApplicationErrorCode
         * @description Deterministic machine-readable error codes for the application intake & normalization pipeline.
         * @enum {string}
         */
        ApplicationErrorCode: "SYNTAX_ERROR" | "INPUT_LIMIT_EXCEEDED" | "UNSUPPORTED_SYNTAX" | "UNSUPPORTED_VARIABLE" | "IMPLICIT_MULTIPLICATION_UNSUPPORTED" | "NON_POLYNOMIAL_INPUT" | "DEGREE_OUT_OF_SCOPE" | "DIVISION_BY_ZERO" | "NORMALIZATION_ERROR" | "METHOD_NOT_FOUND" | "METHOD_NOT_APPLICABLE" | "METHOD_NOT_EXECUTABLE" | "METHOD_EXECUTION_FAILED" | "DOMAIN_CONTRACT_ERROR" | "VERIFICATION_FAILED" | "INTERNAL_ERROR";
        /**
         * CanonicalCoefficientInput
         * @description Direct canonical coefficient parameter input mode for live editing and method switching.
         */
        CanonicalCoefficientInput: {
            /** @description Leading coefficient a */
            a: components["schemas"]["RationalFraction"];
            /** @description Linear coefficient b */
            b: components["schemas"]["RationalFraction"];
            /** @description Constant term c */
            c: components["schemas"]["RationalFraction"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            input_mode: "COEFFICIENTS";
            /**
             * Target Variable
             * @default x
             * @constant
             */
            target_variable: "x";
        };
        /**
         * CanonicalDegenerateProblemView
         * @description Canonical problem representation for degenerate equations (a == 0). Zero discriminant invented.
         */
        CanonicalDegenerateProblemView: {
            a?: components["schemas"]["RationalFraction"];
            b: components["schemas"]["RationalFraction"];
            c: components["schemas"]["RationalFraction"];
            /**
             * Category
             * @default ALGEBRA_QUADRATIC
             * @constant
             */
            category: "ALGEBRA_QUADRATIC";
            /**
             * Classification
             * @enum {string}
             */
            classification: "LINEAR" | "IDENTITY" | "CONTRADICTION";
            /**
             * Equation Latex
             * @description Canonical LaTeX equation e.g. '2x - 4 = 0'
             */
            equation_latex: string;
            linear_root?: components["schemas"]["RationalFraction"] | null;
            /** Problem Id */
            problem_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            problem_type: "DEGENERATE";
            /** Raw Query */
            raw_query?: string | null;
            /** Semantic Revision Hash */
            semantic_revision_hash: string;
        };
        /**
         * CanonicalQuadraticProblemView
         * @description Canonical problem representation for true quadratic equations (a != 0).
         */
        CanonicalQuadraticProblemView: {
            a: components["schemas"]["RationalFraction"];
            b: components["schemas"]["RationalFraction"];
            c: components["schemas"]["RationalFraction"];
            /**
             * Category
             * @default ALGEBRA_QUADRATIC
             * @constant
             */
            category: "ALGEBRA_QUADRATIC";
            /**
             * Classification
             * @default QUADRATIC
             * @constant
             */
            classification: "QUADRATIC";
            discriminant: components["schemas"]["QuadraticDiscriminant"];
            /**
             * Equation Latex
             * @description Canonical LaTeX equation e.g. 'x^2 - 5x + 6 = 0'
             */
            equation_latex: string;
            /** Problem Id */
            problem_id: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            problem_type: "QUADRATIC";
            /** Raw Query */
            raw_query?: string | null;
            /** Semantic Revision Hash */
            semantic_revision_hash: string;
        };
        /**
         * ConceptKnowledge
         * @description Mathematical concept definition across algebra, geometry, and calculus.
         */
        ConceptKnowledge: {
            /**
             * Concept Id
             * @description Stable snake_case concept identifier, e.g. 'concept_discriminant'
             */
            concept_id: string;
            /** Curriculum Refs */
            curriculum_refs?: components["schemas"]["CurriculumRef"][];
            definition: components["schemas"]["LocalizedText"];
            /** Formula Refs */
            formula_refs?: string[];
            /** Method Refs */
            method_refs?: string[];
            /** Prerequisite Concept Ids */
            prerequisite_concept_ids?: string[];
            /** Provenance Refs */
            provenance_refs?: string[];
            /** Related Concept Ids */
            related_concept_ids?: string[];
            title: components["schemas"]["LocalizedText"];
            /**
             * Version
             * @default 1.0.0
             */
            version: string;
        };
        /**
         * CurriculumMappingStatus
         * @description Verification status of curriculum alignment mapping.
         * @enum {string}
         */
        CurriculumMappingStatus: "VERIFIED_MAPPING" | "PROVISIONAL_MAPPING";
        /**
         * CurriculumRef
         * @description Authoritative curriculum standard reference with explicit verification status.
         */
        CurriculumRef: {
            /**
             * Competency Ref
             * @description Specific standard code if verified
             */
            competency_ref?: string | null;
            /**
             * Framework
             * @description Curriculum framework code, e.g. 'GDPT_2018', 'CCSS', 'IB'
             */
            framework: string;
            /**
             * Grade Band
             * @description Grade level identifier, e.g. 'GRADE_9'
             */
            grade_band: string;
            /**
             * Source Document
             * @description Authoritative document title or circular
             */
            source_document: string;
            /**
             * Source Locator
             * @description Chapter, section, or article locator
             */
            source_locator: string;
            /** @description Explicit mapping verification status */
            status: components["schemas"]["CurriculumMappingStatus"];
            /**
             * Subject
             * @description Subject identifier, e.g. 'TOAN'
             */
            subject: string;
            /**
             * Topic
             * @description Curriculum topic code, e.g. 'PHUONG_TRINH_BAC_HAI_MOT_AN'
             */
            topic: string;
        };
        /**
         * DegenerateSolutionView
         * @description Immutable verified solution presentation for degenerate equations (a == 0).
         */
        DegenerateSolutionView: {
            certificate: components["schemas"]["VerificationCertificate"];
            /**
             * Classification
             * @enum {string}
             */
            classification: "LINEAR" | "IDENTITY" | "CONTRADICTION";
            /**
             * Final Answer Latex
             * @description Canonical LaTeX representation of the solution set
             */
            final_answer_latex: string;
            /** @description Exact rational root -c/b when outcome is ONE_REAL_LINEAR_ROOT */
            linear_root?: components["schemas"]["RationalFraction"] | null;
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "ONE_REAL_LINEAR_ROOT" | "INFINITE_REAL_SOLUTIONS" | "NO_REAL_SOLUTIONS_CONTRADICTION";
            /**
             * Verification Scope
             * @default FINAL_SOLUTION
             * @constant
             */
            verification_scope: "FINAL_SOLUTION";
        };
        /**
         * ErrorResponse
         * @description Response state when a fatal intake, parse, normalization, or invariant error occurs.
         */
        ErrorResponse: {
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            error_code: components["schemas"]["ApplicationErrorCode"];
            /** Message En */
            message_en: string;
            /** Message Vi */
            message_vi: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            response_status: "ERROR";
            span?: components["schemas"]["Span"] | null;
        };
        /**
         * ExecutionAvailability
         * @description Whether the solver/worker for this method is currently available to execute.
         * @enum {string}
         */
        ExecutionAvailability: "AVAILABLE" | "UNAVAILABLE";
        /**
         * FormulaKnowledge
         * @description Canonical mathematical formula entity with exact LaTeX template.
         */
        FormulaKnowledge: {
            domain_conditions: components["schemas"]["LocalizedText"];
            /**
             * Formula Id
             * @description Stable unique formula identifier, e.g. 'FORMULA_QUADRATIC_STANDARD'
             */
            formula_id: string;
            /**
             * Latex Template
             * @description LaTeX representation of formula
             */
            latex_template: string;
            /** Provenance Refs */
            provenance_refs?: string[];
            /** Related Concept Ids */
            related_concept_ids?: string[];
            title: components["schemas"]["LocalizedText"];
            /** Variables Description */
            variables_description?: {
                [key: string]: components["schemas"]["LocalizedText"];
            };
            /**
             * Version
             * @default 1.0.0
             */
            version: string;
        };
        /**
         * GraphEdge
         * @description Immutable directed or canonical symmetric relationship between graph nodes.
         */
        GraphEdge: {
            /**
             * Is Directed
             * @description Whether the edge is directed
             * @default true
             */
            is_directed: boolean;
            /**
             * Is Symmetric
             * @description Whether the edge represents a symmetric bidirectional relationship
             * @default false
             */
            is_symmetric: boolean;
            /** @description Optional localized edge label */
            label?: components["schemas"]["LocalizedText"] | null;
            /**
             * Metadata
             * @description Arbitrary metadata dictionary
             */
            metadata?: {
                [key: string]: unknown;
            };
            /** @description Semantic relation type */
            relation_type: components["schemas"]["GraphEdgeType"];
            /**
             * Source
             * @description Source node identifier
             */
            source: string;
            /**
             * Target
             * @description Target node identifier
             */
            target: string;
        };
        /**
         * GraphEdgeType
         * @description Semantic relation types for edges in MKE graph representations.
         * @enum {string}
         */
        GraphEdgeType: "REQUIRES" | "USES_FORMULA" | "USES_THEOREM" | "ALTERNATIVE_TO" | "SPECIAL_CASE_OF" | "RELATED_TO" | "LEARN_BEFORE" | "COMPUTATIONAL_DEPENDENCY";
        /**
         * GraphKind
         * @description Structural classification of graph models.
         * @enum {string}
         */
        GraphKind: "KNOWLEDGE_GRAPH" | "PREREQUISITE_DAG" | "REACTIVE_DEPENDENCY_DAG";
        /**
         * GraphModel
         * @description Top-level container for a validated mathematical knowledge graph or DAG.
         */
        GraphModel: {
            /**
             * Edges
             * @description Ordered list of graph edges
             */
            edges?: components["schemas"]["GraphEdge"][];
            /**
             * Graph Id
             * @description Deterministic unique graph identifier
             */
            graph_id: string;
            /** @description Graph category */
            graph_kind: components["schemas"]["GraphKind"];
            /**
             * Is Acyclic
             * @description Whether the graph is guaranteed to be a Directed Acyclic Graph
             */
            is_acyclic: boolean;
            /**
             * Nodes
             * @description Ordered list of graph nodes
             */
            nodes?: components["schemas"]["GraphNode"][];
            /** @description Bilingual title of the graph */
            title: components["schemas"]["LocalizedText"];
            /**
             * Version
             * @description Graph contract version
             * @default 1.0.0
             */
            version: string;
        };
        /**
         * GraphNode
         * @description Immutable graph node with strict typing and localized label.
         */
        GraphNode: {
            /**
             * Dependency Ref
             * @description Optional reference to reactive computation/parameter ID
             */
            dependency_ref?: string | null;
            /**
             * Knowledge Ref
             * @description Optional reference to underlying knowledge entity ID
             */
            knowledge_ref?: string | null;
            /** @description Bilingual display label */
            label: components["schemas"]["LocalizedText"];
            /**
             * Metadata
             * @description Arbitrary metadata dictionary
             */
            metadata?: {
                [key: string]: unknown;
            };
            /**
             * Node Id
             * @description Deterministic unique prefixed identifier, e.g. 'concept:concept_discriminant'
             */
            node_id: string;
            /** @description Categorical node type */
            node_type: components["schemas"]["GraphNodeType"];
            /**
             * Status
             * @description Optional node status
             */
            status?: string | null;
            /** @description Optional subtitle or explanatory snippet */
            subtitle?: components["schemas"]["LocalizedText"] | null;
        };
        /**
         * GraphNodeType
         * @description Categorical taxonomy for nodes in MKE graph representations.
         * @enum {string}
         */
        GraphNodeType: "CONCEPT" | "METHOD" | "FORMULA" | "THEOREM" | "PARAMETER" | "COMPUTATION";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Observational system health response schema.
         */
        HealthResponse: {
            /** Algebra Authority */
            algebra_authority: string;
            /** Executable Methods Count */
            executable_methods_count: number;
            /** Milestone */
            milestone: string;
            /** Registered Methods Count */
            registered_methods_count: number;
            /** Status */
            status: string;
            /** Supported Input Modes */
            supported_input_modes: string[];
            /** Version */
            version: string;
        };
        /**
         * KnowledgeApiErrorCode
         * @description Specific error codes for knowledge API operations.
         * @enum {string}
         */
        KnowledgeApiErrorCode: "KNOWLEDGE_ENTITY_NOT_FOUND";
        /**
         * KnowledgeApiErrorResponse
         * @description Strict, immutable knowledge API entity error envelope.
         */
        KnowledgeApiErrorResponse: {
            /** Entity Id */
            entity_id: string;
            /** Entity Type */
            entity_type: string;
            /** @default KNOWLEDGE_ENTITY_NOT_FOUND */
            error_code: components["schemas"]["KnowledgeApiErrorCode"];
            /** Message En */
            message_en: string;
            /** Message Vi */
            message_vi: string;
            /**
             * Status
             * @default error
             * @constant
             */
            status: "error";
        };
        /**
         * LocalizedText
         * @description Symmetric bilingual text container requiring explicit non-empty VI and EN content.
         */
        LocalizedText: {
            /**
             * En
             * @description English text content
             */
            en: string;
            /**
             * Vi
             * @description Vietnamese text content
             */
            vi: string;
        };
        /**
         * MathematicalApplicability
         * @description Whether the method is mathematically sound and valid for this problem instance.
         * @enum {string}
         */
        MathematicalApplicability: "APPLICABLE" | "NOT_APPLICABLE" | "UNKNOWN";
        /**
         * MethodKnowledge
         * @description Static epistemological and pedagogical definition of a solution method.
         *
         *     Contains zero equation-specific state (no discriminant, no roots, no runtime applicability).
         */
        MethodKnowledge: {
            /** Applicability Guidance */
            applicability_guidance?: components["schemas"]["LocalizedText"][];
            /** Common Mistakes */
            common_mistakes?: components["schemas"]["LocalizedText"][];
            /** Curriculum Refs */
            curriculum_refs?: components["schemas"]["CurriculumRef"][];
            /** Diagnostic Tips */
            diagnostic_tips?: components["schemas"]["LocalizedText"][];
            formal_description: components["schemas"]["LocalizedText"];
            /** Formula Refs */
            formula_refs?: string[];
            learning_objective: components["schemas"]["LocalizedText"];
            /**
             * Method Id
             * @description Foreign key matching canonical string method_id in MethodRegistry
             */
            method_id: string;
            /** Non Applicability Guidance */
            non_applicability_guidance?: components["schemas"]["LocalizedText"][];
            /** Prerequisite Concept Ids */
            prerequisite_concept_ids?: string[];
            /** Provenance Refs */
            provenance_refs?: string[];
            /** Related Method Ids */
            related_method_ids?: string[];
            summary: components["schemas"]["LocalizedText"];
            /** Theorem Refs */
            theorem_refs?: string[];
            title: components["schemas"]["LocalizedText"];
            /**
             * Version
             * @default 1.0.0
             */
            version: string;
        };
        /**
         * MethodOptionView
         * @description Orthogonal assessment profile of a single registered mathematical method.
         */
        MethodOptionView: {
            execution_availability: components["schemas"]["ExecutionAvailability"];
            /** Has Trace Available */
            has_trace_available: boolean;
            mathematical_applicability: components["schemas"]["MathematicalApplicability"];
            /** Method Id */
            method_id: string;
            /**
             * Pedagogical Priority
             * @default 1
             */
            pedagogical_priority: number;
            pedagogical_recommendation: components["schemas"]["PedagogicalRecommendation"];
            /** Prerequisites */
            prerequisites?: components["schemas"]["PrerequisiteStatus"][];
            /** Reasons */
            reasons?: string[];
            support_status: components["schemas"]["SupportStatus"];
            /** Title Vi */
            title_vi: string;
            verification_capability: components["schemas"]["VerificationCapability"];
        };
        /**
         * NoExecutionReasonCode
         * @description Machine-readable reason for why no trace execution occurred in analyzed response.
         * @enum {string}
         */
        NoExecutionReasonCode: "METHOD_NOT_APPLICABLE" | "METHOD_NOT_EXECUTABLE" | "DEGENERATE_EXACT_SOLUTION";
        /**
         * PedagogicalRecommendation
         * @description Pedagogical recommendation level for Vietnamese secondary learners.
         * @enum {string}
         */
        PedagogicalRecommendation: "RECOMMENDED" | "NEUTRAL" | "DISCOURAGED";
        /**
         * PrerequisiteStatus
         * @description Evaluation status for a single pedagogical/method prerequisite.
         */
        PrerequisiteStatus: {
            /** Description Vi */
            description_vi: string;
            /** Is Satisfied */
            is_satisfied: boolean;
            /** Prerequisite Id */
            prerequisite_id: string;
        };
        /**
         * QuadraticDiscriminant
         * @description Exact discriminant data structure with squarefree kernel analysis.
         */
        QuadraticDiscriminant: {
            /** @description Rational factor s >= 0 such that sqrt(Delta) = s * sqrt(d) */
            extracted_factor?: components["schemas"]["RationalFraction"] | null;
            /**
             * Is Negative
             * @description True if Delta < 0
             */
            is_negative: boolean;
            /**
             * Is Positive
             * @description True if Delta > 0
             */
            is_positive: boolean;
            /**
             * Is Rational Square
             * @description True if Delta is a square in Q
             */
            is_rational_square: boolean;
            /**
             * Is Zero
             * @description True if Delta == 0
             */
            is_zero: boolean;
            /** @description Exact rational sqrt(Delta) when is_rational_square is True */
            square_root_rational?: components["schemas"]["RationalFraction"] | null;
            /**
             * Squarefree Kernel
             * @description Squarefree integer d >= 1 such that Delta = s^2 * d (d=1 if rational square)
             */
            squarefree_kernel?: number | null;
            /** @description Exact rational value of Delta = b^2 - 4ac */
            value: components["schemas"]["RationalFraction"];
        };
        /**
         * RationalFraction
         * @description Canonical serializable representation of an exact rational number p/q.
         */
        RationalFraction: {
            /**
             * Denominator
             * @description Canonical integer denominator > 0
             * @default 1
             */
            denominator: number;
            /**
             * Numerator
             * @description Canonical integer numerator
             */
            numerator: number;
        };
        /**
         * RawEquationInput
         * @description Raw mathematical text equation input mode.
         */
        RawEquationInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            input_mode: "RAW_TEXT";
            /**
             * Raw Query
             * @description Raw equation string e.g. 'x^2 - 5*x + 6 = 0'
             */
            raw_query: string;
            /**
             * Target Variable
             * @default x
             * @constant
             */
            target_variable: "x";
        };
        /**
         * RealRootValue
         * @description Exact representation of a real root in Q or Q(sqrt(d)).
         */
        RealRootValue: {
            /**
             * Approximate Float
             * @description Floating-point approximation for visualization only
             */
            approximate_float?: number | null;
            /**
             * Latex Str
             * @description Canonical LaTeX representation of the root
             */
            latex_str: string;
            /**
             * Radicand
             * @description Squarefree radicand d > 1
             */
            radicand?: number | null;
            rational_value?: components["schemas"]["RationalFraction"] | null;
            root_type: components["schemas"]["SolutionRootType"];
            /** @description Rational base u in u + v*sqrt(d) */
            surd_base?: components["schemas"]["RationalFraction"] | null;
            /** @description Rational coefficient v in u + v*sqrt(d) */
            surd_factor?: components["schemas"]["RationalFraction"] | null;
        };
        /**
         * SolutionOutcome
         * @description Mathematical outcome category for equation solving.
         * @enum {string}
         */
        SolutionOutcome: "TWO_DISTINCT_REAL_ROOTS" | "ONE_REPEATED_REAL_ROOT" | "NO_REAL_ROOTS" | "ONE_REAL_LINEAR_ROOT" | "INFINITE_REAL_SOLUTIONS" | "NO_REAL_SOLUTIONS_CONTRADICTION";
        /**
         * SolutionRootType
         * @description Representation type of a real root.
         * @enum {string}
         */
        SolutionRootType: "RATIONAL" | "REAL_SURD" | "NO_REAL_ROOT";
        /**
         * SolutionStep
         * @description Step in a verified solution trace.
         */
        SolutionStep: {
            /** Explanation Vi */
            explanation_vi: string;
            /** Latex Expression */
            latex_expression: string;
            /** Rule Or Theorem Used */
            rule_or_theorem_used?: string | null;
            /** Step Number */
            step_number: number;
            /** Sub Steps */
            sub_steps?: components["schemas"]["SolutionStep"][];
            /** Why This Step Vi */
            why_this_step_vi?: string | null;
        };
        /**
         * SolutionTrace
         * @description Complete structured solution trace for an algebraic problem.
         */
        SolutionTrace: {
            /** Final Answer Latex */
            final_answer_latex: string;
            /**
             * Is Complete
             * @default true
             */
            is_complete: boolean;
            /** Method Id */
            method_id: string;
            /** Roots */
            roots?: components["schemas"]["RealRootValue"][];
            solution_outcome: components["schemas"]["SolutionOutcome"];
            /** Steps */
            steps?: components["schemas"]["SolutionStep"][];
        };
        /**
         * SolveRequest
         * @description Application intake request container for equation analysis and solving.
         */
        SolveRequest: {
            /** Input Payload */
            input_payload: components["schemas"]["RawEquationInput"] | components["schemas"]["CanonicalCoefficientInput"];
            /**
             * Schema Version
             * @default 1.0.0
             * @constant
             */
            schema_version: "1.0.0";
            /**
             * Selected Method Id
             * @description Explicit method selection ID. If None, highest-priority applicable method is executed.
             */
            selected_method_id?: string | null;
        };
        /**
         * SolvedResponse
         * @description Response state when problem is analyzed AND an applicable/available method is verified.
         */
        SolvedResponse: {
            /** Available Methods */
            available_methods: components["schemas"]["MethodOptionView"][];
            problem: components["schemas"]["CanonicalQuadraticProblemView"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            response_status: "SOLVED";
            /** Selected Method Id */
            selected_method_id: string;
            solution: components["schemas"]["VerifiedSolutionView"];
        };
        /**
         * Span
         * @description Immutable character span [start, end) within source text.
         */
        Span: {
            /** End */
            end: number;
            /** Start */
            start: number;
        };
        /**
         * SupportStatus
         * @description Whether the method is implemented and supported in the MKE solver engine.
         * @enum {string}
         */
        SupportStatus: "SUPPORTED" | "UNSUPPORTED";
        /**
         * TheoremKnowledge
         * @description Mathematical theorem entity with formal hypotheses and conclusions.
         */
        TheoremKnowledge: {
            /** Conclusions */
            conclusions?: components["schemas"]["LocalizedText"][];
            /**
             * Formal Statement Latex
             * @description Formal mathematical statement in LaTeX
             */
            formal_statement_latex: string;
            /** Hypotheses */
            hypotheses?: components["schemas"]["LocalizedText"][];
            /** Provenance Refs */
            provenance_refs?: string[];
            /** Related Concept Ids */
            related_concept_ids?: string[];
            statement: components["schemas"]["LocalizedText"];
            /**
             * Theorem Id
             * @description Stable unique theorem identifier, e.g. 'THEOREM_VIETA_RELATIONS'
             */
            theorem_id: string;
            title: components["schemas"]["LocalizedText"];
            /**
             * Version
             * @default 1.0.0
             */
            version: string;
        };
        /**
         * TransportErrorCode
         * @description Specific error codes for transport/HTTP failures occurring prior to or around application execution.
         * @enum {string}
         */
        TransportErrorCode: "MALFORMED_JSON" | "REQUEST_VALIDATION_FAILED" | "PAYLOAD_TOO_LARGE" | "UNSUPPORTED_MEDIA_TYPE" | "API_NOT_FOUND" | "INTERNAL_TRANSPORT_ERROR";
        /**
         * TransportErrorResponse
         * @description Strict, immutable transport error envelope.
         */
        TransportErrorResponse: {
            /** Details */
            details?: {
                [key: string]: unknown;
            };
            /** Message En */
            message_en: string;
            /** Message Vi */
            message_vi: string;
            transport_error_code: components["schemas"]["TransportErrorCode"];
            /**
             * Transport Status
             * @default ERROR
             * @constant
             */
            transport_status: "ERROR";
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VerificationCapability
         * @description Capability of independent verification for this method's trace.
         * @enum {string}
         */
        VerificationCapability: "HOST_VERIFIABLE" | "UNVERIFIED" | "NOT_APPLICABLE";
        /**
         * VerificationCertificate
         * @description Tamper-evident token certifying independent host mathematical verification.
         */
        VerificationCertificate: {
            /** Algebraic Identities Passed */
            algebraic_identities_passed?: string[];
            /** Certificate Id */
            certificate_id: string;
            /**
             * Certificate Signature
             * @description Deprecated alias for integrity_fingerprint. Note: this is an unkeyed SHA-256 digest, NOT a cryptographic signature.
             */
            certificate_signature?: string | null;
            /**
             * Integrity Fingerprint
             * @description Deterministic unkeyed SHA-256 digest of canonical certificate verification payload (content identifier, not a digital signature)
             */
            integrity_fingerprint: string;
            /**
             * Multiplicity Verified
             * @default false
             */
            multiplicity_verified: boolean;
            /**
             * No Real Roots Verified
             * @default false
             */
            no_real_roots_verified: boolean;
            outcome: components["schemas"]["VerificationOutcome"];
            /** Problem Hash */
            problem_hash: string;
            /** Residual Checks */
            residual_checks?: string[];
            /**
             * Verified At Utc
             * Format: date-time
             */
            verified_at_utc?: string;
            /**
             * Verifier Name
             * @default MKE_HOST_INDEPENDENT_VERIFIER_V1
             */
            verifier_name: string;
            /**
             * Verifier Version
             * @default 1.0.0
             */
            verifier_version: string;
            /**
             * Vieta Relations Checked
             * @default false
             */
            vieta_relations_checked: boolean;
        };
        /**
         * VerificationOutcome
         * @description Result of independent deterministic host verification.
         * @enum {string}
         */
        VerificationOutcome: "VERIFIED_COMPLETE" | "VERIFICATION_FAILED" | "NOT_APPLICABLE";
        /**
         * VerifiedSolutionView
         * @description Verified execution result and step-by-step trace.
         */
        VerifiedSolutionView: {
            certificate: components["schemas"]["VerificationCertificate"];
            /** Final Answer Latex */
            final_answer_latex: string;
            /** Method Id */
            method_id: string;
            outcome: components["schemas"]["SolutionOutcome"];
            /** Roots */
            roots?: components["schemas"]["RealRootValue"][];
            trace: components["schemas"]["SolutionTrace"];
            /**
             * Verification Scope
             * @default FINAL_SOLUTION
             * @constant
             */
            verification_scope: "FINAL_SOLUTION";
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    solve_algebra_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SolveRequest"];
            };
        };
        responses: {
            /** @description Successful mathematical analysis or client domain error */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolvedResponse"] | components["schemas"]["AnalyzedNoExecutionResponse"] | components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Malformed JSON payload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransportErrorResponse"];
                };
            };
            /** @description Payload exceeds 64 KiB limit */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransportErrorResponse"];
                };
            };
            /** @description Unsupported Content-Type */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransportErrorResponse"];
                };
            };
            /** @description DTO schema validation failure */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransportErrorResponse"];
                };
            };
            /** @description Internal application or transport failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"] | components["schemas"]["TransportErrorResponse"];
                };
            };
        };
    };
    health_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System health and runtime registry metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_knowledge_concept_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                concept_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Concept knowledge details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConceptKnowledge"];
                };
            };
            /** @description Knowledge concept entity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal transport failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransportErrorResponse"];
                };
            };
        };
    };
    get_knowledge_formula_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                formula_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Formula knowledge details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FormulaKnowledge"];
                };
            };
            /** @description Knowledge formula entity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal transport failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransportErrorResponse"];
                };
            };
        };
    };
    get_knowledge_graph_v1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Full mathematical knowledge graph */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GraphModel"];
                };
            };
            /** @description Internal transport failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransportErrorResponse"];
                };
            };
        };
    };
    get_knowledge_method_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                method_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Method knowledge details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MethodKnowledge"];
                };
            };
            /** @description Knowledge method entity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal transport failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransportErrorResponse"];
                };
            };
        };
    };
    get_knowledge_theorem_v1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                theorem_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Theorem knowledge details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TheoremKnowledge"];
                };
            };
            /** @description Knowledge theorem entity not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["KnowledgeApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
            /** @description Internal transport failure */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TransportErrorResponse"];
                };
            };
        };
    };
}
